const $=s=>document.querySelector(s);const days=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];let tasks=JSON.parse(localStorage.getItem('uobTasks')||'[]');
const today=new Date();$('#dueDate').value=new Date(today.getTime()+3*86400000).toISOString().slice(0,10);
function save(){localStorage.setItem('uobTasks',JSON.stringify(tasks));renderTasks()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function esc(v){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderTasks(){const box=$('#taskList');$('#taskCount').textContent=`${tasks.length} ${tasks.length===1?'مهمة':'مهام'}`;if(!tasks.length){box.innerHTML='<div class="empty-state"><span>📚</span><b>لا توجد مهام بعد</b><p>أضف أول مهمة ليبدأ بناء خطتك.</p></div>';return}box.innerHTML=tasks.map((t,i)=>`<div class="task-item"><div><span class="badge">${esc(t.type)}</span><b>${esc(t.course)} • ${esc(t.title)}</b><small>التسليم: ${t.due} • ${['','سهلة','متوسطة','مرتفعة'][t.diff]}</small></div><button class="delete-task" data-i="${i}" aria-label="حذف المهمة">×</button></div>`).join('');box.querySelectorAll('.delete-task').forEach(b=>b.onclick=()=>{tasks.splice(+b.dataset.i,1);save()})}
$('#plannerForm').onsubmit=e=>{e.preventDefault();tasks.push({course:$('#course').value.trim().toUpperCase(),type:$('#taskType').value,title:$('#taskTitle').value.trim(),due:$('#dueDate').value,diff:+$('#difficulty').value});save();$('#taskTitle').value='';toast('تمت إضافة المهمة بنجاح')};
function minutes(v){const [h,m]=v.split(':').map(Number);return h*60+m}function fmt(n){return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function generate(){if(!tasks.length){toast('أضف مهمة واحدة على الأقل');return}const start=minutes($('#startTime').value),end=minutes($('#endTime').value),len=+$('#sessionLength').value,rest=$('#restDay').value; if(end<=start||end-start<len){toast('تحقق من وقت البداية والنهاية');return}const now=new Date();const ranked=[...tasks].sort((a,b)=>{let da=(new Date(a.due)-now)/86400000,db=(new Date(b.due)-now)/86400000;return (b.diff*4-db)-(a.diff*4-da)});let columns=days.map((name,i)=>({name,i,slots:[]}));let currentDay=now.getDay();let cursor=start;ranked.forEach((t,idx)=>{let sessions=Math.max(1,t.diff+(t.type==='اختبار'?1:0));for(let s=0;s<sessions;s++){let tries=0;while((String(currentDay)===rest||cursor+len>end)&&tries<8){currentDay=(currentDay+1)%7;cursor=start;tries++}columns[currentDay].slots.push({time:fmt(cursor),task:t});cursor+=len+10;if(cursor+len>end){currentDay=(currentDay+1)%7;cursor=start}}});$('#weekGrid').innerHTML=columns.map(d=>`<article class="day-column"><h4>${d.name}<small>${d.slots.length} جلسات</small></h4>${d.slots.length?d.slots.map(s=>`<div class="slot"><time>${s.time}</time><b>${esc(s.task.course)}</b><small>${esc(s.task.title)} • ${len} د</small></div>`).join(''):'<div class="rest">راحة أو وقت متاح</div>'}</article>`).join('');const first=ranked[0];$('#insight').innerHTML=`✦ <b>لماذا هذا الترتيب؟</b> بدأنا بمهمة <b>${esc(first.course)}</b> لأن موعدها قريب أو صعوبتها أعلى، مع فاصل 10 دقائق بين الجلسات.`;$('#scheduleWrap').classList.remove('hidden');$('#scheduleWrap').scrollIntoView({behavior:'smooth',block:'start'});toast('تم إنشاء خطتك الذكية')}
$('#generateBtn').onclick=generate;$('#regenerateBtn').onclick=()=>{tasks.reverse();generate()};$('#clearBtn').onclick=()=>{tasks=[];save();$('#scheduleWrap').classList.add('hidden');toast('تم مسح المهام')};$('#printBtn').onclick=()=>window.print();
$('#demoBtn').onclick=loadDemo;function loadDemo(){const d=new Date();const iso=n=>new Date(d.getTime()+n*86400000).toISOString().slice(0,10);tasks=[{course:'ITCS113',type:'اختبار',title:'مراجعة البرمجة والحلقات',due:iso(2),diff:3},{course:'ACC112',type:'واجب',title:'تمارين الفصل الرابع',due:iso(4),diff:2},{course:'MATHS101',type:'مراجعة',title:'حل مسائل المصفوفات',due:iso(6),diff:2}];save();toast('تم تحميل المثال');document.querySelector('#planner').scrollIntoView({behavior:'smooth'})}
$('#howBtn').onclick=()=>{document.querySelector('#features').scrollIntoView({behavior:'smooth'})};$('#menuBtn').onclick=()=>{const n=$('#nav');n.classList.toggle('open');$('#menuBtn').setAttribute('aria-expanded',n.classList.contains('open'))};renderTasks();